idf_component_register(
    SRCS
        "main.cpp"
        "app_mode.cpp"
        "audio_chime.cpp"
        "board_peripherals.cpp"
        "music_screen.cpp"
        "stats_screen.cpp"
        "clock_screen.cpp"
        "pomodoro_screen.cpp"
        "sand_screen.cpp"
        "comic_screen.cpp"
        "http_api.cpp"
        "ota_update.cpp"
        "board_client.cpp"
        "network_manager.cpp"
        "provisioning_portal.cpp"
        "provisioning_display.cpp"
        "ui_error.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        u8g2_st7305
        esp_timer
        esp_pm
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_client
        esp_http_server
        app_update
        qrcode
        json
        mbedtls
        driver
        esp_adc
        mdns
        esp_codec_dev
        pngle
        lwip
)
