#!/usr/bin/env python3
"""Regenerate index_html_gz.h from the INDEX_HTML raw string in the sketch.

The dashboard page (~15 KB) is too big to send reliably as one blocking
server.send_P over the device's WiFi link — it truncated ~25% of the time even
with the Higher-Bandwidth lwIP variant, because a 15 KB push needs the TCP
window to drain mid-write and a lossy/sleepy link stalls it. Gzipping the page
to ~5 KB lets the whole body fit in one send-buffer fill, so the write never
stalls. handleRoot() serves this blob with Content-Encoding: gzip.

INDEX_HTML in clawdmeter_esp8266.ino stays the human-editable source of truth.
After editing it, run this script to refresh the compressed header:

    python3 esp8266/tools/gen_index_gz.py

Stdlib only; no venv.
"""
import gzip
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SKETCH = HERE.parent / "clawdmeter_esp8266" / "clawdmeter_esp8266.ino"
OUT = HERE.parent / "clawdmeter_esp8266" / "index_html_gz.h"

# Match: const char INDEX_HTML[] PROGMEM = R"HTML( ...body... )HTML";
PATTERN = re.compile(
    r'const\s+char\s+INDEX_HTML\[\]\s+PROGMEM\s*=\s*R"HTML\((.*?)\)HTML";',
    re.DOTALL,
)

# GUARD: the gzipped page MUST fit in one Higher-Bandwidth lwIP (ip=hb2f) TCP
# send-buffer fill, or handleRoot's single blocking send_P stalls mid-page on a
# lossy link and the dashboard truncates again — the exact bug fixed in 2742d66
# (docs/postmortems/dashboard-truncated-send.md). hb2f's TCP_SND_BUF is ~5840 B
# (4xMSS); cap at 5120 to keep a safety margin under that one-buffer ceiling.
# If you bust this, shrink the dashboard (trim inline CSS/JS) rather than raising
# the cap — raising it reintroduces the multi-buffer stall.
MAX_GZ_BYTES = 5120


def main() -> int:
    src = SKETCH.read_text(encoding="utf-8")
    m = PATTERN.search(src)
    if not m:
        print("ERROR: could not find INDEX_HTML raw string in", SKETCH, file=sys.stderr)
        return 1
    html = m.group(1).encode("utf-8")
    # mtime=0 for reproducible output (no timestamp in the gzip header).
    blob = gzip.compress(html, compresslevel=9, mtime=0)

    if len(blob) > MAX_GZ_BYTES:
        print(
            f"ERROR: gzipped dashboard is {len(blob)} B, over the {MAX_GZ_BYTES} B "
            f"guard.\n  The page must fit one ip=hb2f TCP send-buffer fill or "
            f"handleRoot's send_P\n  stalls mid-page and the dashboard truncates "
            f"again (see\n  docs/postmortems/dashboard-truncated-send.md). Trim the "
            f"dashboard HTML;\n  do NOT just raise MAX_GZ_BYTES.",
            file=sys.stderr,
        )
        return 1

    lines = [
        "// AUTO-GENERATED by esp8266/tools/gen_index_gz.py — do not edit by hand.",
        "// Source of truth is the INDEX_HTML raw string in clawdmeter_esp8266.ino.",
        "// Regenerate after editing the dashboard HTML:",
        "//     python3 esp8266/tools/gen_index_gz.py",
        "#pragma once",
        f"// {len(html)} bytes HTML -> {len(blob)} bytes gzip",
        f"static const unsigned int INDEX_HTML_GZ_LEN = {len(blob)};",
        "static const unsigned char INDEX_HTML_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(html)} B HTML -> {len(blob)} B gzip)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
