#!/usr/bin/env bash
# Regenerate esp8266/clawdmeter_esp8266/thai_font.h — the bitmap fonts the MUSIC
# screen uses to render YouTube Music titles/artists in Thai (and Latin).
#
# Why this exists: Arduino_GFX's built-in 5x7 font is ASCII-only, and its stock
# drawChar() indexes glyphs with an 8-bit char, so it cannot reach Thai code
# points (U+0E00+). We rasterize a real Thai typeface into Adafruit GFXfont
# tables (PROGMEM/flash) and blit them with our own 16-bit-codepoint renderer
# (see musicGfx* in clawdmeter_esp8266.ino). Thai combining marks (tone marks,
# upper/lower vowels) carry xAdvance==0 with negative xOffsets in this font, so a
# faithful per-glyph blit stacks them over the base consonant with no special
# combining logic.
#
# Four sub-fonts are emitted: a TITLE size (large, scrolls) and an ARTIST size
# (smaller, static), each in a Latin (U+0020..U+007E) and a Thai (U+0E00..U+0E7F)
# range. The renderer picks Latin vs Thai per code point.
#
# Requires: Adafruit_GFX's fontconvert built against freetype. macOS:
#   FT=$(brew --prefix freetype)
#   cc "$ADAFRUIT/fontconvert/fontconvert.c" -o /tmp/fontconvert \
#      -I"$FT/include/freetype2" -L"$FT/lib" -lfreetype
set -euo pipefail

FONT="${THAI_TTF:-/System/Library/Fonts/Supplemental/Ayuthaya.ttf}"
FC="${FONTCONVERT:-/tmp/fontconvert}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/clawdmeter_esp8266/thai_font.h"
TITLE_SIZE="${TITLE_SIZE:-18}"
ARTIST_SIZE="${ARTIST_SIZE:-14}"

[ -x "$FC" ] || { echo "fontconvert not found at $FC (build it first, see header)"; exit 1; }
[ -f "$FONT" ] || { echo "font not found: $FONT"; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# fontconvert <ttf> <size> <firstCodepoint> <lastCodepoint>
"$FC" "$FONT" "$TITLE_SIZE"  32   126  > "$tmp/title_latin.h"
"$FC" "$FONT" "$TITLE_SIZE"  3584 3711 > "$tmp/title_thai.h"
"$FC" "$FONT" "$ARTIST_SIZE" 32   126  > "$tmp/artist_latin.h"
"$FC" "$FONT" "$ARTIST_SIZE" 3584 3711 > "$tmp/artist_thai.h"

python3 - "$OUT" "$FONT" "$TITLE_SIZE" "$ARTIST_SIZE" \
  "$tmp/title_latin.h:MusicTitleLatin" \
  "$tmp/title_thai.h:MusicTitleThai" \
  "$tmp/artist_latin.h:MusicArtistLatin" \
  "$tmp/artist_thai.h:MusicArtistThai" <<'PY'
import re, sys
out, font, tsz, asz, *specs = sys.argv[1:]
parts = []
for spec in specs:
    path, target = spec.rsplit(":", 1)
    txt = open(path).read()
    m = re.search(r'const GFXfont (\w+) PROGMEM', txt)
    base = m.group(1)                       # e.g. Ayuthaya18pt7b
    txt = txt.replace(base, target)         # rename Bitmaps/Glyphs/struct in one go
    txt = re.sub(r'\n// Approx\..*', '', txt)
    parts.append(txt.strip())
header = (
    "// AUTO-GENERATED by esp8266/tools/gen_thai_font.sh — do not edit by hand.\n"
    f"// Source: {font}  (title {tsz}px, artist {asz}px)\n"
    "// Adafruit GFXfont tables for the MUSIC screen's Thai/Latin renderer.\n"
    "#ifndef THAI_FONT_H\n#define THAI_FONT_H\n#include \"gfxfont.h\"\n\n"
)
open(out, "w").write(header + "\n\n".join(parts) + "\n\n#endif // THAI_FONT_H\n")
print("wrote", out)
PY

echo "Sub-font flash sizes (bitmaps+glyphs, approx):"
grep -E "Approx" "$tmp"/*.h 2>/dev/null || true